apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-crud-cm
data:
  APP_PORT: "5522"
  NODE_ENV: development
  DB_HOST: 10.99.39.68
  DB_PORT: "3306"
  DB_NAME: development
  DB_USER: root
  DB_PASSWORD: root
