apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefull
spec:
  selector:
    matchLabels:
      name: mysql
  serviceName: mysql-statefull-service
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pv-claim
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306